// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UIRiotClientMainWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            WinControl uILolstaticaakamaihdneDocument = this.UILolstaticaakamaihdneWindow.UIChromeLegacyWindowWindow.UILolstaticaakamaihdneDocument;
            WinPane uIItemPane1 = this.UILolstaticaakamaihdneWindow.UIItemPane.UIItemPane1;
            #endregion

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(151, 328));

            // Type 'tiktiktik115{Tab}{LShiftKey}Longpro' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Type '123' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(274, 847));

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(1268, 135));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -76, 582);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(878, 928));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(343, 436));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(253, 372));

            // Type 'alksdnflkaq' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1105, 592));

            // Type 'qwew' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys3, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(880, 768));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(881, 710));

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1544, 739));

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1405, 379));

            // Type 'Long{Tab}{LShiftKey}Long{RShiftKey}@gmai.cc{Left}{Left}{Left}l{Tab}090909123' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys, ModifierKeys.None);

            // Type '4' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys1, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1562, 746));

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1423, 417));

            // Type '090912301232' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys2, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1627, 502));

            // Type '01200{Back}23' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys3, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1368, 606));

            // Type '20{Left}' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys4, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1505, 608));

            // Type '{Back}11{Back}{Back}2000' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys5, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1512, 736));

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1336, 452));

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1393, 387));

            // Type '10' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Keyboard.SendKeys(uILolstaticaakamaihdneDocument, this.RecordedMethod1Params.UILolstaticaakamaihdneDocumentSendKeys6, ModifierKeys.None);

            // Click 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
            Mouse.Click(uILolstaticaakamaihdneDocument, new Point(1533, 741));

            // Click pane
            Mouse.Click(uIItemPane1, new Point(1907, 0));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1101, 752));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIRiotClientMainWindow UIRiotClientMainWindow
        {
            get
            {
                if ((this.mUIRiotClientMainWindow == null))
                {
                    this.mUIRiotClientMainWindow = new UIRiotClientMainWindow();
                }
                return this.mUIRiotClientMainWindow;
            }
        }
        
        public UILolstaticaakamaihdneWindow UILolstaticaakamaihdneWindow
        {
            get
            {
                if ((this.mUILolstaticaakamaihdneWindow == null))
                {
                    this.mUILolstaticaakamaihdneWindow = new UILolstaticaakamaihdneWindow();
                }
                return this.mUILolstaticaakamaihdneWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIRiotClientMainWindow mUIRiotClientMainWindow;
        
        private UILolstaticaakamaihdneWindow mUILolstaticaakamaihdneWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'tiktiktik115{Tab}{LShiftKey}Longpro' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "tiktiktik116{Tab}{LShiftKey}Longpro";
        
        /// <summary>
        /// Type '123' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "123";
        
        /// <summary>
        /// Type 'alksdnflkaq' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "alksdnflkaq";
        
        /// <summary>
        /// Type 'qwew' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys3 = "qwew";
        
        /// <summary>
        /// Type 'Long{Tab}{LShiftKey}Long{RShiftKey}@gmai.cc{Left}{Left}{Left}l{Tab}090909123' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys = "Long{Tab}{LShiftKey}Long{RShiftKey}@gmai.cc{Left}{Left}{Left}l{Tab}090909123";
        
        /// <summary>
        /// Type '4' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys1 = "4";
        
        /// <summary>
        /// Type '090912301232' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys2 = "090912301232";
        
        /// <summary>
        /// Type '01200{Back}23' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys3 = "01200{Back}23";
        
        /// <summary>
        /// Type '20{Left}' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys4 = "20{Left}";
        
        /// <summary>
        /// Type '{Back}11{Back}{Back}2000' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys5 = "{Back}11{Back}{Back}2000";
        
        /// <summary>
        /// Type '10' in 'lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-...' document
        /// </summary>
        public string UILolstaticaakamaihdneDocumentSendKeys6 = "10";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRiotClientMainWindow : WinWindow
    {
        
        public UIRiotClientMainWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Riot Client Main";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "RCLIENT";
            this.WindowTitles.Add("Riot Client Main");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "117489352";
            this.WindowTitles.Add("Riot Client Main");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Riot Client Main");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILolstaticaakamaihdneWindow : WinWindow
    {
        
        public UILolstaticaakamaihdneWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = @"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends - Cá nhân - Microsoft​ Edge";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#1 - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#2 - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#3 - Cá nhân - Microsoft​ Edge");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIItemPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new UIItemPane(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow;
        
        private UIItemPane mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "44657824";
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#1 - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#2 - Cá nhân - Microsoft​ Edge");
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#3 - Cá nhân - Microsoft​ Edge");
            #endregion
        }
        
        #region Properties
        public WinControl UILolstaticaakamaihdneDocument
        {
            get
            {
                if ((this.mUILolstaticaakamaihdneDocument == null))
                {
                    this.mUILolstaticaakamaihdneDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUILolstaticaakamaihdneDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUILolstaticaakamaihdneDocument.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends - Cá nhân - Microsoft​ Edge");
                    this.mUILolstaticaakamaihdneDocument.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#1 - Cá nhân - Microsoft​ Edge");
                    this.mUILolstaticaakamaihdneDocument.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#2 - Cá nhân - Microsoft​ Edge");
                    this.mUILolstaticaakamaihdneDocument.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#3 - Cá nhân - Microsoft​ Edge");
                    #endregion
                }
                return this.mUILolstaticaakamaihdneDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUILolstaticaakamaihdneDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemPane : WinPane
    {
        
        public UIItemPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#3 - Cá nhân - Microsoft​ Edge");
            #endregion
        }
        
        #region Properties
        public WinPane UIItemPane1
        {
            get
            {
                if ((this.mUIItemPane1 == null))
                {
                    this.mUIItemPane1 = new WinPane(this);
                    #region Search Criteria
                    this.mUIItemPane1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemPane1.WindowTitles.Add(@"lolstatic-a.akamaihd.net/rso-mobile-ui/0.3.38/vng-registration.vi_VN.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXVpZCI6IjA2ZjFiYzEzLWQwZDMtNTZkZC05OThhLTZlNmU1ZjUxN2Y2ZCIsInZuZ0FwcElkIjoiaGYiLCJwcm9kdWN0SWQiOiJsZWFndWVfb2ZfbGVnZW5kcyIsImlhdCI6MTcwMzY1NjE2MiwiZXhwIjoxNzA3MjU2MTYyLCJhdWQiOiJ2bmciLCJpc3MiOiJodHRwczovL3NlYS5hcGkuYWNjb3VudC5yaW90Z2FtZXMuY29tIn0.wTIHqrduOjC7VL7UKrBzoRmaM0d82wY4pBR9m_yMFZI&api_url=https%3A%2F%2Fsea.api.account.riotgames.com&redirect_uri=riotclient%3A%2F%2Fvng%2Fv1%2Fstatus%2Frecheck%2Fleague_of_legends#3 - Cá nhân - Microsoft​ Edge");
                    #endregion
                }
                return this.mUIItemPane1;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIItemPane1;
        #endregion
    }
}
